#!/bin/sh
# Copyright (C) 2016 Velocloud Inc
# Copyright (C) 2016 Aleksander Morgado <aleksander@aleksander.es>

# Load hotplug common utilities
. /usr/share/ModemManager/modemmanager.common

# We require a device name
[ -n "$DEVNAME" ] || exit

# Always make sure the rundir exists
mkdir -m 0755 -p "${MODEMMANAGER_RUNDIR}"

# Report TTY
mm_log "info" "${ACTION} serial interface ${DEVNAME}: event processed"
mm_report_event "${ACTION}" "${DEVNAME}" "tty" "/sys${DEVPATH}"

if [ "$ACTION" = "add" ]; then
    if [ -e "/sys/class/net/wwan0" ]; then
        /sbin/ip link set wwan0 up
        mm_log "info" "Proactive set 'wwan0' link UP to ModemManager detection."
    fi
fi
