port: 7890
redir-port: 7891
socks-port: 7892
mixed-port: 7893
tproxy-port: 7894

allow-lan: true
bind-address: '*'
routing-mark: 0x100
mode: rule
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: ui
secret: anu
geodata-mode: true
geodata-loader: memconservative
global-client-fingerprint: chrome
keep-alive-interval: 15
tcp-concurrent: true
unified-delay: true
tun:
  enable: false
  stack: gvisor
  device: Meta
  dns-hijack:
    - any:53
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
  skip-domain:
    - '+.microsoft.com'
    - '+.windows.com'
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:1053
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  fallback:
    - 1.0.0.1
    - 8.8.4.4
    - 149.112.112.112
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9
  proxy-server-nameserver:
    - 112.215.203.246
    - 112.215.203.247
    - 112.215.203.248
    - 112.215.203.254
    - 112.215.198.248
    - 112.215.198.254
profile:
  store-selected: true
  store-fake-ip: false
proxy-providers:
  ID:
    type: file
    path: ./proxy_providers/id.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
  MIX:
    type: file
    path: ./proxy_providers/mix.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 120
proxy-groups:
- name: AUTO-ID-MIX
  type: fallback
  disable-udp: false
  use:
  - ID
  - MIX
  url: http://www.gstatic.com/generate_204
  interval: 120
- name: LB-MIX-ID
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - MIX
  - ID
  url: http://www.gstatic.com/generate_204
  interval: 120
- name: SERVER-UMUM
  type: select
  disable-udp: false
  proxies:
  - AUTO-ID-MIX
  - LB-MIX-ID
  - DIRECT
- name: SERVER-INDO
  type: select
  disable-udp: false
  proxies:
  - AUTO-ID-MIX
  - DIRECT
- name: SERVER-GAME
  type: select
  disable-udp: false
  proxies:
  - AUTO-ID-MIX
  - DIRECT
- name: BLOCK-IKLAN
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - SERVER-UMUM
rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./rule_providers/game.yaml
  PortGame:
    type: file
    behavior: classical
    path: ./rule_providers/portgame.yaml
  Umum:
    type: file
    behavior: classical
    path: ./rule_providers/umum.yaml
  indo:
    type: file
    behavior: classical
    path: ./rule_providers/indo.yaml
  Sosmed:
    type: file
    behavior: classical
    path: ./rule_providers/sosmed.yaml
  Streaming:
    type: file
    behavior: classical
    path: ./rule_providers/streaming.yaml
  Bankid:
    type: file
    behavior: domain
    path: ./rule_providers/bankid.yaml
  Tiktok:
    type: file
    behavior: domain
    path: ./rule_providers/tiktok.yaml
  Meta:
    type: file
    behavior: domain
    path: ./rule_providers/meta.yaml
rules:
- RULE-SET,Umum,SERVER-UMUM
- RULE-SET,Game,SERVER-GAME
- RULE-SET,PortGame,SERVER-GAME
- RULE-SET,indo,SERVER-INDO
- RULE-SET,Sosmed,SERVER-INDO
- RULE-SET,Streaming,SERVER-UMUM
- RULE-SET,Bankid,SERVER-INDO
- RULE-SET,Tiktok,SERVER-UMUM
- RULE-SET,Meta,SERVER-INDO
- MATCH,SERVER-UMUM